# Generated by Django 4.2.30 on 2026-05-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_alter_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jokes', to='jokes.tag'),
        ),
    ]
